Enable builds for ARM64
feedzai/make-lightgbm pull request #14
Opened 2023-09-14 14:30 UTC by artpdr

- Generates artifacts for AMD64 and ARM64 by default
- ARM64 compilation is done using emulation, hence it's slow but doesn't require a new toolchain and system root files that would take lots of space in the repo and possibly have legal issues
- There's the possibility of computing only for AMD64 which is way faster and most likely what's desirable for testing quick developments

2023-09-14 16:08 UTC, AlbertoEAF requested changes
We could refactor this a bit but as we've talked let's ship this ASAP. Trivial style comments only

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +echo_stage "Launching container AMD64..."
```suggestion
echo_stage "Launching AMD64 container..."
```

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +  echo_stage "Launching container ARM64..."
```suggestion
  echo_stage "Launching ARM64 container..."
```

2023-09-14 16:08 UTC, AlbertoEAF commented on make_patch.sh
> +cp $(ldd "${CWD}/build/amd64/lib_lightgbm.so" | awk '/libgomp/{print $3}') "${CWD}/build/amd64/libgomp.so.1.0.0"
We need to add a comment to this file (maybe here and in the header) and a note on the README (in the respective section) with a caveat that this currently only applies for AMD64 parts of the build.

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +echo_stage "Building LightGBM AMD64 $LIGHTGBM_VERSION..."
```suggestion
echo_stage "Building AMD64 LightGBM $LIGHTGBM_VERSION..."
```

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +echo_bold "Running container AMD64: $container_amd64"
```suggestion
echo_bold "Running AMD64 container: $container_amd64"
```

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +  echo_stage "Building LightGBM ARM64 $LIGHTGBM_VERSION..."
```suggestion
  echo_stage "Building ARM64 LightGBM $LIGHTGBM_VERSION..."
```

2023-09-14 16:08 UTC, AlbertoEAF commented on docker/make_docker_image.sh
> +    docker build -t lightgbm-ci-build-env-arm64 --platform=arm64 lightgbm-ci-build-env-arm64
broken indentation, same below, use spaces

2023-09-14 16:08 UTC, AlbertoEAF commented on make.sh
> +ARCH_BUILD="${ARCH_BUILD:-multi}"
move the new lines to a new isolated paragraph after line 38, so the lgbm version configuration is all together as before.

2023-09-14 16:31 UTC, AlbertoEAF commented
Also, we need to add some README detailing how to run these docker ARM builds locally. It's not that trivial and could be useful to other developers.

2023-09-15 07:28 UTC, artpdr commented on docker/make_docker_image.sh
> +    docker build -t lightgbm-ci-build-env-arm64 --platform=arm64 lightgbm-ci-build-env-arm64
done

2023-09-15 07:28 UTC, artpdr commented on make.sh
> +ARCH_BUILD="${ARCH_BUILD:-multi}"
done

2023-09-15 07:28 UTC, artpdr commented on make_patch.sh
> +cp $(ldd "${CWD}/build/amd64/lib_lightgbm.so" | awk '/libgomp/{print $3}') "${CWD}/build/amd64/libgomp.so.1.0.0"
Added a comment to the header and readme.

2023-09-15 09:44 UTC, AlbertoEAF requested changes

2023-09-15 09:44 UTC, AlbertoEAF commented on docker/lightgbm-ci-build-env-arm64/Dockerfile
> + && curl -OL https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4-SHA-256.txt.asc \
This is not very safe if there is any future tampering. 

Put this `.asc` file directly in in the `docker/lightgbm-ci-build-env-arm64/` folder and copy it to the image and verify the checksum through that file.

2023-09-15 09:46 UTC, AlbertoEAF commented on make.sh
> +ARCH_BUILD="${ARCH_BUILD:-multi}"
did you push? looks the same

2023-09-15 09:54 UTC, artpdr commented on docker/lightgbm-ci-build-env-arm64/Dockerfile
> + && curl -OL https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4-SHA-256.txt.asc \
We verify this asc below using gpg

2023-09-15 10:01 UTC, AlbertoEAF requested changes

2023-09-15 10:01 UTC, AlbertoEAF commented on make.sh
> +    echo_stage "Launching container ARM64..."
```suggestion
    echo_stage "Launching ARM64 container..."
```

2023-09-15 10:01 UTC, AlbertoEAF commented on make.sh
> +    echo_stage "Building LightGBM ARM64 $LIGHTGBM_VERSION..."
```suggestion
    echo_stage "Building ARM64 LightGBM $LIGHTGBM_VERSION..."
```

2023-09-15 10:23 UTC, AlbertoEAF approved these changes

2023-09-15 10:23 UTC, merged